name: backend-ci

on:
  push:
    branches: [ main ]   # 与 backend_github_branch 一致
  workflow_dispatch: {}

env:
  BACKEND_AWS_REGION: us-east-1                  # 与 Terraform 一致
  BACKEND_ECR_REPO_PREFIX: microshop             # 与 Terraform 一致
  BACKEND_SERVICES: api-gateway,users-service,orders-service,inventory-service

permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [api-gateway, users-service, orders-service, inventory-service]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <把 Terraform 输出的 backend_gha_role_arn 填这里>
          aws-region: ${{ env.BACKEND_AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & push with Jib
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          REGISTRY="${{ steps.ecr.outputs.registry }}"
          IMAGE="$REGISTRY/${{ env.BACKEND_ECR_REPO_PREFIX }}/${{ matrix.service }}:$IMAGE_TAG"
          echo "Building $IMAGE"

          # 针对顶层多模块：-pl 指定模块，-am 自动构建依赖
          mvn -q -DskipTests -pl ${{ matrix.service }} -am \
            -Dimage=$IMAGE \
            com.google.cloud.tools:jib-maven-plugin:3.4.0:build

      # （可选）把服务→镜像 的映射产成工件，后续给 Argo/Helm 用
      - name: Emit image mapping
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          REGISTRY="${{ steps.ecr.outputs.registry }}"
          IMAGE="$REGISTRY/${{ env.BACKEND_ECR_REPO_PREFIX }}/${{ matrix.service }}:$IMAGE_TAG"
          echo "{\"${{ matrix.service }}\":\"$IMAGE\"}" > "image-${{ matrix.service }}.json"

      - uses: actions/upload-artifact@v4
        with:
          name: images
          path: image-*.json
